### ISSUE TITLE
update readme to reflect 2019 in example playbook

### ISSUE THREAD

**Issue by Xalorous** [ansible-lockdown/Windows-2019-STIG#1]
Expected: 
```
- hosts: servers
  roles:
     - role: win-2k19-stig
       when:
            - ansible_os_family == 'Windows'
            - ansible_distribution | regex_search('(Server 2019)')
```

Experienced instead:
```
- hosts: servers
  roles:
     - role: win-2k16-stig
       when:
            - ansible_os_family == 'Windows'
            - ansible_distribution | regex_search('(Server 2016)')
```

Recommended fix:
change to:
```
- hosts: servers
  roles:
     - role: win-2k19-stig
       when:
            - ansible_os_family == 'Windows'
            - ansible_distribution | regex_search('(Server 2019)')
```
