### ISSUE TITLE
Put roles into blocks to prevent unwanted execution - force failure

### ISSUE THREAD

**Issue by schnipdip** [ansible-lockdown/Windows-2019-STIG#2]
Issue:

If your playbook contains `ignore_errors: yes`, then the possibility of erroring out and the play failing won't happen if a conditional check isn't matching. Therefore, as a failsafe conditional check, a `block` module is needed to prevent unnecessary task execution. 

The return code values need to be registered in `/tasks/main.yml`

Create a boolean conditional check on the registered values before processing `prelim, cat1,cat2,cat3`.

Code:

```
block:
  - name: Include the preliminary tasks
    include_tasks: prelim.yml
    tags:
        - prelim_tasks

  - name: Execute the category 1 (highest severity) tasks
    import_tasks: cat1.yml
    when: win2019stig_cat1_patch | bool
    tags:
        - cat1
        - high

  - name: Execute the category 2 (medium severity) tasks
    import_tasks: cat2.yml
    when: win2019stig_cat2_patch | bool
    tags:
        - cat2
        - medium

  - name: Execute the category 3 (lowest severity) tasks
    import_tasks: cat3.yml
    when: win2019stig_cat3_patch | bool
    tags:
        - cat3
        - medium
when: 
  - os_version_check is true 
  - ansible_version_check is true
```
